### PR TITLE
Migrate documentation to MkDocs

### LINKED ISSUE #24: Move Documentation website to Docusaurus or Hugo
Currently the documentation uses Jekyll, and it is pretty weak when it comes to product-grade documentation (macros, external sourcing for docs-as-code, etc., etc.). I think it would be preferable to have another documentation engine, preferably Docusaurus or Hugo. I find Docusaurus much more powerful and sustainable, but IIUIC @tomakehurst prefers Hugo. Subject for a discussion

## References

- https://docusaurus.io/
- https://gohugo.io/

### LINKED ISSUE #28: Add a /community/Slack page
At the moment we have Slack invite links all over the place, and it is not sustainable. Some links actually point to the UP9 Slack which is rather dead... Once the link expires, we will have dead links all over the place too. So, we need a page for Slack landing that describes _How to join_, references key documents like CoC, and probably provides a channel map

### PR DESCRIPTION
**Pull request by oleg-nenashev**
For #24 . This is a big WiP prototype

Closes:

- Closes #24 
- Closes #28 
- Closes https://github.com/wiremock/wiremock.org/issues/169

Other key features

- Search
- Better Mobile navigation

## Preview

https://oleg-nenashev.github.io/wiremock.org/

image

## TODOs

- [x] Initial MkDocs setup
- [x] Split and relocate images
- [x] Move code tabs to the native engine
- [x] Setup CI
- [x] Setup staging site
- [x] Fix redirects within docs
- [x] Fix images
- [x] Ensure section links and breadcrumbs work fine
- [x] Fix sitemap generation for docs
- [x] Fix Docs Landing page rendering or move it back to the Jekyll site
- [x] Fix Header and Footer
- [x] Add OpenGraph rendering
- [x] Fix OpenAPI specification rendering and source it from the repo
- [x] Fix version number rendering/propagation to MkDocs
- [x] Move events pages to the new engine
- [x] Move external resources to the new engine
- [x] Configure Google Analytics
- [ ] Configure MS Clarity (Custom script needed)
- [x] Align the header with the old website
- [x] Move Support pages to the documentation engine
- [x] Fix the docs site header on mobile screens 

## Production deployment TODO

- [ ] Update deployment pipelines to follow staging
- [ ] Update Google Analytics and Clarity tags

## Submitter checklist

- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] If the change against WireMock 2 functionality (incompatible with WireMock 3),
      it is submitted against the [2.x](https://github.com/wiremock/wiremock.org/tree/2.x) branch
- [x] The repository's code style is followed (see the contributing guide)

_Details: [Contributor Guide](https://github.com/wiremock/wiremock.org/blob/main/CONTRIBUTING.md)_

### CODE REVIEW

**Comment by tomakehurst** [comment]
Closing this as it's been merged and superseded via branching

**Comment by oleg-nenashev** [comment]
It was not merged BTW, an alternative implementation was done instead.
It's your decision tho

**Comment by tomakehurst** [comment]
We'll get there at some point in the next couple of months I think. Just hasn't been the bandwidth to get it over the line yet.

**Comment by oleg-nenashev** [comment]
Ack, thanks for the clarification! I remain available to help if any small
changes are needed. I will probably take some parts of the implementation
for the Gradle community subsite that basically has a similar Jekyll+MkDocs
structure. So I will keep improving templates and layouts

**Comment by tomakehurst** [comment]
We've actually dropped Jekyll completely from it now on our branch. That was one of the reasons for delaying the switch i.e. the vestiges of Jekyll were still a pain to live with.

**Comment by oleg-nenashev** [comment]
I totally support that move. Thumbs up! :)
In my case, it might have to live for some time, but hopefully not for long

**Pull request closed without merging**
