### PR TITLE
Update spring-boot.md

### LINKED ISSUE #116: Issue on Using with Spring Boot
### Page

/docs/solutions/spring-boot/

### Details

link is not available
https://wiremock.org/3.x/docs/solutions/solutions/jvm
for the useful pages area

### Suggested Edits

Provide a valid link

### References

https://wiremock.org/3.x/docs/solutions/spring-boot/

### PR DESCRIPTION
**Pull request by Smartmind12**
Updated link address for Java and JVM in the Springboot page

## References

- Closes #116 

## Submitter checklist

- [X] The PR request is well described and justified, including the body and the references
- [X] The PR title represents the desired changelog entry
- [X] If the change against WireMock 2 functionality (incompatible with WireMock 3),
      it is submitted against the [2.x](https://github.com/wiremock/wiremock.org/tree/2.x) branch
- [X] The repository's code style is followed (see the contributing guide)

_Details: [Contributor Guide](https://github.com/wiremock/wiremock.org/blob/main/CONTRIBUTING.md)_

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
what us wrong with the current link? They need to be relative when possible

**Comment by Smartmind12** [comment]
> what us wrong with the current link? They need to be relative when possible

The current link takes you to a invalid 404 page as shown in the screenshot. So i have updated the link to tkae it to the correct page.

Screenshot 2023-10-02 at 12 10 23 PM

**Review by oleg-nenashev — COMMENTED** [review]
I suggest `../jvm` to keep the things relative then

**Review by Smartmind12 — COMMENTED** [review]
I believe if we remove the path of 3.x/docs then the issue will arise again of failur of reaching the site…i will test it out and let you if this works!

**Comment by oleg-nenashev** [comment]
> I believe if we remove the path of 3.x/docs then the issue will arise again of failur of reaching the site…i will test it out and let you if this works!

That's unlikely if all the branches are synced. But let's see

**Comment by tomakehurst** [comment]
We're migrating to a new docs stack and this link is correct under the new scheme

**Pull request closed without merging**
