### PR TITLE
Existing Documentation Restructuring

### PR DESCRIPTION
**Pull request by oleg-nenashev**
This change restructures the existing documentation to improve navigation, and to enable better learning path for newcomers. It also changes sections so that we can add more contents in the future

## Changes summary

- [x] - New Overview page
- [x] - Replace old "Getting Started" by the JUnit4 Tutorial and a listing of other tutorials including external ones
- [x] - Move rare use-cases to "Advanced": Java 1.7, running in servlet containers. We do not wont to promote them on the front
- [x] - Consolidate all WireMock Standalone docs in a dedicated section, prioritize the Docker use-case. Also add a page for administrative APIs overview
- [x] - Move Spring Boot and Android to "Java Usage" for now
- [x] - Revamp the navigation bar to  provide better structure

## New navbar

image

## Old Navbar

image

### CODE REVIEW

**Comment by tomakehurst** [comment]
Do you think JUnit 5 might be better for getting started?

I'd assume most folks are using that now rather than 4.x.

**Comment by oleg-nenashev** [comment]
> Do you think JUnit 5 might be better for getting started?

This is why I keep the page just `junit`. Once we have a guide for JUnit 5, I will add it and move JUnit4 to another page

**Comment by tomakehurst** [comment]
We have https://wiremock.org/docs/junit-jupiter/ for JUnit 5, could that not be used right now?

**Comment by oleg-nenashev** [comment]
@tomakehurst That page is documentation, not a quickstart. It will take some some time, and I do not want to dop it as a part of this PR

**Pull request merged**
