### PR TITLE
Add b alternative

### PR DESCRIPTION
**Pull request by limptwiglet**
## B with full height hero boxes:
image

## C with images:
image

## Todo
- [x] Get correct OSS image for hero block

## Submitter checklist

- [ ] The PR request is well described and justified, including the body and the references
- [ ] The PR title represents the desired changelog entry
- [ ] If the change against WireMock 2 functionality (incompatible with WireMock 3),
      it is submitted against the [2.x](https://github.com/wiremock/wiremock.org/tree/2.x) branch
- [ ] The repository's code style is followed (see the contributing guide)

_Details: [Contributor Guide](https://github.com/wiremock/wiremock.org/blob/main/CONTRIBUTING.md)_

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Why do we want to include a screenshot of the same website like that? Maybe we could just put "By The Technology" Grid image?

**Comment by limptwiglet** [comment]
> Why do we want to include a screenshot of the same website like that? Maybe we could just put "By The Technology" Grid image?

Its temporary, I just put something in there for style reasons. It will be replaced

**Comment by oleg-nenashev** [comment]
ok

**Review by oleg-nenashev — APPROVED** [review]
Please make sure to create the A/B testing ticket after the merge

**Pull request merged**
