### PR TITLE
docs: optionally fail request if several mappings match

### PR DESCRIPTION
**Pull request by tomasbjerre**
## References

https://github.com/wiremock/wiremock/pull/2263

## Submitter checklist

- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [x] The repository's code style is followed (see the contributing guide)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@tomasbjerre please rebase it against the https://github.com/wiremock/wiremock.org/tree/3.0.0-beta branch

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Requesting changes, the destination branch needs to be updated. I created https://github.com/wiremock/wiremock.org/pull/128 to have it explicitly in the pull request template

**Review by oleg-nenashev — APPROVED** [review]
Will merge once the feature is out. Maybe we should start creating a "HowTo?" page with the use-cases like that so that are more discoverable

**Comment by tomasbjerre** [comment]
I think it should be mentioned here:
https://wiremock.org/docs/configuration/

But I dont know what headline to use for that.

There is also [this](https://github.com/wiremock/wiremock/issues/1622#issuecomment-1633828242)  new feature that (if approved) is related to this.

**Pull request closed without merging**
