### PR TITLE
Add Frequently Asked Questions page

### PR DESCRIPTION
**Pull request by picimako**
This PR contains the introduction of an FAQ page. It could be used to store answesr to various questions that might not necessarily fit into other documentation topic, and to preserve knowledge from the WireMock Community Slack.

Notes:
- If you think the currently included question and answer would be a better fit for a different page, let me know.
- Please advise on the page title and meta information, if it should be something else, or should be placed somewhere else.

## Submitter checklist

- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [ ] If the change against WireMock 2 functionality (incompatible with WireMock 3),
      it is submitted against the [2.x](https://github.com/wiremock/wiremock.org/tree/2.x) branch
- [x] The repository's code style is followed (see the contributing guide)

_Details: [Contributor Guide](https://github.com/wiremock/wiremock.org/blob/main/CONTRIBUTING.md)_

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
I would call the page "faq" in the URL. Note that there is also a FAQ section on the landing, and maybe we want to copy the content from there. 

image

**Comment by picimako** [comment]
Oh, I was not aware of that FAQ page. I'll change the url to 'faq' and move those contents over. Thank you.

**Comment by picimako** [comment]
@oleg-nenashev I added the changes.
Could you also please check my question above regarding the mapping structuring question?

**Review by oleg-nenashev — APPROVED** [review]
+1 from me, sorry for the review delay

**Comment by oleg-nenashev** [comment]
The build failure is unrelated, merging
Thanks a lot @picimako !

**Pull request merged**
