### PR TITLE
Update styles to be more inline with wiremock branding

### PR DESCRIPTION
**Pull request by limptwiglet**
Update site styles to be more inline with wiremock branding.

image
image
image

Mobile:
image
image
image
image
image
image

## Submitter checklist

- [x] The PR request is well described and justified, including the body and the references
- [x] The PR title represents the desired changelog entry
- [ ] If the change against WireMock 2 functionality (incompatible with WireMock 3),
      it is submitted against the [2.x](https://github.com/wiremock/wiremock.org/tree/2.x) branch
- [x] The repository's code style is followed (see the contributing guide)

_Details: [Contributor Guide](https://github.com/wiremock/wiremock.org/blob/main/CONTRIBUTING.md)_

### CODE REVIEW

**Review by oleg-nenashev — COMMENTED** [review]
Some screenshots would be nice, hard to review instead

**Comment by limptwiglet** [comment]
> Some screenshots would be nice, hard to review instead

Updated with screenshots

**Review by oleg-nenashev — COMMENTED** [review]
I think the current "Downloads" layout is better than the one suggested in the PR. No objections for other entries

**Comment by limptwiglet** [comment]
> I think the current "Downloads" layout is better than the one suggested in the PR. No objections for other entries

Agreed, latest commit reverts and improves the previous downloads section

**Review by oleg-nenashev — APPROVED** [review]
Lgtm

**Pull request merged**
